name: greentech_app
description: "GREEN TECH - Monitoreo inteligente de cultivos"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0

  # Gráficas para dashboard e histórico
  fl_chart: ^0.68.0

  # Permite seleccionar imágenes para foto de perfil
  image_picker: 0.8.9

  # Guardar ruta/ajustes simples en el dispositivo
  shared_preferences: ^2.2.0

  # Acceso a rutas de archivos (para persistir la imagen localmente)
  path_provider: ^2.0.15

  # Firebase (descomenta cuando conectes tu proyecto real)
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.6
  google_sign_in: ^6.1.0
  # cloud_firestore: ^4.17.4

  # HTTP para consumir tu API / MQTT bridge de los ESP32

  # Formateo de fechas ("Hace 5 seg", etc.)
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  # assets:
  #   - assets/images/logo.png
